# Generated by Django 5.2.2 on 2025-11-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_datetime', models.DateTimeField()),
                ('fahrenheit', models.DecimalField(decimal_places=4, max_digits=7)),
                ('celsius', models.DecimalField(decimal_places=4, max_digits=7)),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('key_slug', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
