# Generated by Django 5.2.2 on 2025-08-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(help_text='General description of this recipe.')),
                ('goes_with', models.TextField(help_text='ideas on entrees, sides, or desserts this recipe would normally be paired with')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=1, help_text='0=worst, 10=best', max_digits=3, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', related_query_name='ratings', to='meal_planning.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('unit_size', models.CharField(max_length=1024)),
                ('unit_amount', models.DecimalField(decimal_places=4, max_digits=9)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', related_query_name='ingredients', to='meal_planning.recipe')),
            ],
        ),
    ]
