# Generated by Django 5.2.2 on 2025-08-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['recipe__name', 'category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name']},
        ),
    ]
