# Generated by Django 5.2.2 on 2025-08-24 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0002_alter_ingredient_options_alter_recipe_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Is this for the dough, filling, topping, etc?', max_length=1024)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_groups', related_query_name='ingredient_groups', to='meal_planning.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', related_query_name='ingredients', to='meal_planning.ingredientgroup'),
        ),
    ]
