# Generated by Django 5.2.2 on 2025-08-24 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0003_ingredientgroup_ingredient_ingredient_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', related_query_name='ingredients', to='meal_planning.ingredientgroup'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', related_query_name='ingredients', to='meal_planning.recipe'),
        ),
    ]
