# Generated by Django 5.2.2 on 2025-08-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0004_alter_ingredient_ingredient_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['ingredient_group__recipe__name', 'ingredient_group__name', 'category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='ingredientgroup',
            options={'ordering': ['recipe__name', 'name']},
        ),
    ]
