# Generated by Django 5.2.2 on 2025-08-26 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0005_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_multiplier', models.DecimalField(decimal_places=4, max_digits=9)),
                ('comment', models.TextField(blank=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipliers', related_query_name='multipliers', to='meal_planning.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_amount_adjustment', models.DecimalField(decimal_places=4, default=0, help_text='If the amount is not linear, use this to make tweaks', max_digits=9)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_planning.ingredient')),
                ('recipe_multiplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', related_query_name='ingredients', to='meal_planning.recipemultiplier')),
            ],
        ),
    ]
