# Generated by Django 5.2.2 on 2025-08-26 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0006_recipemultiplier_ingredientmultiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientmultiplier',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipliers', related_query_name='multipliers', to='meal_planning.ingredient'),
        ),
    ]
