# Generated by Django 5.2.2 on 2025-08-31 01:07

import django.db.models.deletion
from django.db import migrations, models




class Migration(migrations.Migration):
    FORWARD_SQL = """
    INSERT INTO meal_planning_recipetype(name)
    VALUES ('Entree'), ('Side'), ('Bread'), ('Other Dessert'), ('Cookie'), ('Cake'), ('Other');"""
    REVERSE_SQL = "DELETE FROM meal_planning_recipetype;"

    dependencies = [
        ('meal_planning', '0007_alter_ingredientmultiplier_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ServingCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made', models.DateField()),
                ('serving_size', models.CharField(help_text='Describe the scoop used or piece size', max_length=1024)),
                ('count', models.DecimalField(decimal_places=4, max_digits=9)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_counts', related_query_name='serving_counts', to='meal_planning.recipe')),
                ('recipe_multiplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_counts', related_query_name='serving_counts', to='meal_planning.recipemultiplier')),
            ],
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
