# Generated by Django 5.2.2 on 2025-08-31 01:27

import django.db.models.deletion
from django.db import migrations, models


def set_default_recipe_type(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    RecipeType = apps.get_model("meal_planning", "RecipeType")
    Recipe = apps.get_model("meal_planning", "Recipe")
    other_type, _ = RecipeType.objects.get_or_create(name="Other")
    Recipe.objects.filter(recipe_type__isnull=True).update(recipe_type=other_type)


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0008_recipetype_servingcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', related_query_name='recipes', to='meal_planning.recipetype'),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_recipe_type, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='recipes',
                                    related_query_name='recipes', to='meal_planning.recipetype'),
        ),
    ]
