# Generated by Django 5.2.5 on 2025-08-09 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ItemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_dow', models.CharField(choices=[('_', 'No Specific Day'), ('W', 'Wednesday'), ('T', 'Thursday'), ('F', 'Friday'), ('NW', 'Next Wednesday'), ('NT', 'Next Thursday'), ('NF', 'Next Friday'), ('O', 'Other')], default='_', max_length=1024)),
                ('for_other_dow', models.TextField(blank=True, help_text="For when for_dow is 'other'.", null=True)),
                ('donated', models.BooleanField(default=False, help_text='Item was donated.  Price is likely 0.')),
                ('estimate', models.BooleanField(default=False, help_text='No accurate price available.  This is a best-guess.')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('usage_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usage.usagegroup')),
            ],
        ),
    ]
