# Generated by Django 5.2.5 on 2025-08-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemusage',
            name='usage_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_items', related_query_name='used_items', to='usage.usagegroup'),
        ),
    ]
