# Generated by Django 5.2.5 on 2025-08-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_alter_itemusage_usage_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemusage',
            name='for_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
