# Generated by Django 5.2.5 on 2025-08-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0003_itemusage_for_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemusage',
            name='for_other_dow',
            field=models.CharField(blank=True, help_text="A specific date for when for_dow is 'other'.", max_length=15, null=True),
        ),
    ]
