# Generated by Django 5.2.5 on 2025-08-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0004_alter_itemusage_for_other_dow'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemusage',
            name='category',
            field=models.CharField(choices=[('congregate', 'Congregate'), ('bakery', 'Bakery'), ('nonfood', 'Nonfood'), ('other', 'Other')], default='congregate', max_length=1024),
        ),
        migrations.AddField(
            model_name='usagegroup',
            name='name_on_form',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
