# Generated by Django 5.2.5 on 2025-08-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0005_itemusage_category_usagegroup_name_on_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemusage',
            name='recorded_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
