# Generated by Django 5.2.5 on 2025-08-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0006_itemusage_recorded_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagegroup',
            name='form_order',
            field=models.IntegerField(default=0),
        ),
    ]
