# Generated by Django 5.2.5 on 2025-08-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0007_usagegroup_form_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemusage',
            name='comment',
            field=models.TextField(blank=True, help_text='A further description for this specific instance of usage', null=True),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='meal_part',
            field=models.CharField(choices=[('entree', 'Entree'), ('side', 'Side'), ('dessert', 'Dessert'), ('bread', 'Bread'), ('other', 'Other')], default='other', max_length=64),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='quantity',
            field=models.IntegerField(default=0, help_text='How many on the packages were used'),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='used_size',
            field=models.CharField(blank=True, help_text='The size of each package used', max_length=1024, null=True),
        ),
    ]
