# Generated by Django 5.2.5 on 2025-08-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0008_itemusage_comment_itemusage_meal_part_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivenDateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_date', models.DateField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
