# Generated by Django 5.2.2 on 2025-10-22 04:36

import django.db.models.deletion
import market.models.order
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField(default=market.models.order.today)),
                ('time_ordered', models.TimeField(default=market.models.order.now)),
                ('date_made', models.DateField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('who', models.CharField(blank=True, default='', max_length=100)),
                ('sale_price', models.DecimalField(decimal_places=4, default=0, help_text='sale price for all items in the order', max_digits=9)),
                ('material_cost', models.DecimalField(decimal_places=4, default=0, help_text='cost of materials for all items in the order.', max_digits=9)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('expected_time', models.TimeField(blank=True, null=True)),
                ('who_is_picking_up', models.CharField(blank=True, default='', help_text="If different than 'who'", max_length=100)),
                ('reason_for_order', models.CharField(blank=True, default='', help_text='Because people keep asking me.', max_length=100)),
                ('how_paid', models.CharField(blank=True, default='', help_text='card/cash/gift certificate.  Is this even needed?', max_length=100)),
                ('contact_number', models.CharField(blank=True, default='', help_text='In case there is an issue and/or pickup is delayed', max_length=100)),
                ('discount', models.DecimalField(decimal_places=4, default=0, help_text='discount applied to the order.', max_digits=9)),
                ('discount_text', models.CharField(blank=True, default='', help_text='Brief explanation of the discount.', max_length=100)),
                ('discounted_price', models.DecimalField(decimal_places=4, default=0, help_text='sale price minus discount.', max_digits=9)),
            ],
            options={
                'ordering': ['expected_date', 'who', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_items', related_query_name='market_items', to='market.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='items', related_query_name='items', to='market.tag')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_position', models.IntegerField(default=0)),
                ('item_str', models.CharField(blank=True, help_text='Backup of str(item) in case the item is deleted.', max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('pack_quantity', models.IntegerField(default=12, help_text='count per bag/plate.')),
                ('sale_price_per_pack', models.DecimalField(decimal_places=4, max_digits=9)),
                ('sale_price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('material_cost_per_pack', models.DecimalField(blank=True, decimal_places=4, default=0, help_text='cost of materials for a single pack.', max_digits=9)),
                ('material_cost', models.DecimalField(blank=True, decimal_places=4, default=0, help_text='cost of materials for the order.', max_digits=9)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', related_query_name='line_items', to='market.order')),
            ],
            options={
                'ordering': ['order', 'line_item_position'],
            },
        ),
    ]
