# Generated by Django 5.2.2 on 2025-06-09 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_item_search_criteria', models.JSONField(help_text='overly complicated JSON object used to suggest this item for new source items.')),
                ('description', models.TextField(help_text="General description of the item and how it'd likely be used.")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_date', models.DateField()),
                ('po_text', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.source')),
            ],
        ),
        migrations.CreateModel(
            name='SourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discontinued', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=255)),
                ('source_category', models.CharField(help_text="probably won't agree with Item.category", max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.source')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField(default=1)),
                ('quantity_delivered', models.IntegerField(default=0)),
                ('remote_stock', models.BooleanField(default=False)),
                ('unit_size', models.CharField(max_length=255)),
                ('per_pack_price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('extended_price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('tax', models.DecimalField(decimal_places=4, max_digits=9)),
                ('per_weight_price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('per_pack_weights', models.DecimalField(decimal_places=4, max_digits=9)),
                ('total_weight', models.DecimalField(decimal_places=4, max_digits=9)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.sourceitem')),
            ],
        ),
    ]
