# Generated by Django 5.2.2 on 2025-06-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceitem',
            name='common_name',
            field=models.CharField(blank=True, default='', help_text="A more friendly version of the name.  Would this just be the Item's name?", max_length=1024),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='cryptic_name',
            field=models.CharField(default='', help_text='The horribly abbreviated and truncated name as it appears on the invoice.', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='expanded_name',
            field=models.CharField(blank=True, default='', help_text='The horribly abbreviated and truncated name but with as many of the abbreviations and truncations fixed.', max_length=1024),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='extra_number',
            field=models.CharField(blank=True, default='', help_text='Some sources have a second identifying number/code.', max_length=255),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='item_number',
            field=models.CharField(blank=True, default='', help_text='The main number/code used to identify this product at this source.', max_length=255),
        ),
    ]
