# Generated by Django 5.2.2 on 2025-06-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sourceitem_common_name_sourceitem_cryptic_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source_item_search_criteria',
            field=models.JSONField(blank=True, help_text='overly complicated JSON object used to suggest this item for new source items.', null=True),
        ),
    ]
