# Generated by Django 5.2.2 on 2025-06-28 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_source_item_search_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(help_text='oz, floz, lb, pint, gallon', max_length=1024)),
                ('amount', models.DecimalField(decimal_places=4, help_text="the quantity of units.  The '15.5' in '15.5floz'", max_digits=9)),
            ],
            options={
                'ordering': ['unit', 'amount'],
            },
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='active',
            field=models.BooleanField(default=True, help_text='Products sometimes change their packaging.  This option allows the unit size to remain tied to the source item but no longer selectable.'),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='allow_split_pack',
            field=models.BooleanField(default=True, help_text="Can this package be split?  As in, '4x 1 gallon' be split and purchase '1x 1 gallon'?"),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='quantity',
            field=models.IntegerField(default=1, help_text='How many of the UnitSize is there in this package?'),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='common_name',
            field=models.CharField(blank=True, default='', help_text='A more friendly version of the name.  This might be slang we use so not always Item.name', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='item_number',
            field=models.CharField(blank=True, default='', help_text='The main number/code used to identify this product at this source for this unit size.', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.unitsize'),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='unit_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.unitsize'),
        ),
    ]
