# Generated by Django 5.2.2 on 2025-06-28 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_unitsize_sourceitem_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceitem',
            name='subunit_size',
            field=models.ForeignKey(help_text='For when the box contains packs of multiple units.  Like a box with 8 packs of 6 pudding cups.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bob', related_query_name='bob', to='inventory.unitsize'),
        ),
    ]
