# Generated by Django 5.2.2 on 2025-06-29 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_sourceitem_subunit_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit_size',
        ),
        migrations.RemoveField(
            model_name='sourceitem',
            name='discontinued',
        ),
        migrations.AddField(
            model_name='source',
            name='customer_number',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='subunit_size',
            field=models.ForeignKey(blank=True, help_text='For when the box contains packs of multiple units.  Like a box with 8 packs of 6 pudding cups.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bob', related_query_name='bob', to='inventory.unitsize'),
        ),
    ]
