# Generated by Django 5.2.2 on 2025-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_item_unit_size_remove_sourceitem_discontinued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='customer_number',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
