# Generated by Django 5.2.2 on 2025-06-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_source_customer_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlineitem',
            options={'ordering': ['line_item_number']},
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='unit_size',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Is there anything noteworthy about this order but not a specific item?'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='damaged',
            field=models.BooleanField(default=False, help_text='Item damaged but not necessarily sent back.'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='expect_backorder_delivery',
            field=models.BooleanField(default=False, help_text='Sysco substitutes out-of-stock items.  GemState sends them later.'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='line_item_number',
            field=models.IntegerField(default=0, help_text='the ordering on the invoice'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Anything remarkable about this specific item?'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='rejected',
            field=models.BooleanField(default=False, help_text='Item sent back because of damage, incorrect, etc.'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='rejected_reason',
            field=models.TextField(blank=True, help_text='Why was this item sent back?', null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='per_pack_weights',
            field=models.JSONField(default=list),
        ),
    ]
