# Generated by Django 5.2.2 on 2025-06-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='per_pack_weights',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='per_weight_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
    ]
