# Generated by Django 5.2.2 on 2025-07-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_orderlineitem_per_pack_weights_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='unitsize',
            options={'ordering': ['unit']},
        ),
        migrations.RemoveField(
            model_name='unitsize',
            name='amount',
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='subunit_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="the quantity of subunits.  The '15.5' in '15.5floz'", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='subunit_amount_text',
            field=models.CharField(blank=True, help_text="An amount that isn't a single number.  Like '9-12#'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='unit_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="the quantity of units.  The '15.5' in '15.5floz'", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='unit_amount_text',
            field=models.CharField(blank=True, help_text="An amount that isn't a single number.  Like '9-12#'.", max_length=255, null=True),
        ),
    ]
