# Generated by Django 5.2.2 on 2025-07-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_squashed_0011_alter_category_options_alter_unitsize_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='customer_number',
            field=models.JSONField(blank=True, default=list, help_text='List of customer numbers for this source.  Cannot have a Source per customer number as that would duplicate the crap out of SourceItems.', null=True),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='cryptic_name',
            field=models.CharField(help_text='The horribly abbreviated and truncated name as it appears on the invoice.', max_length=1024),
        ),
    ]
