# Generated by Django 5.2.2 on 2025-07-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_source_customer_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlineitem',
            options={'ordering': ['-order__delivered_date', 'order__source', 'line_item_number']},
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='raw_import_data',
            field=models.JSONField(blank=True, help_text="Raw JSON data that contributed to this object's creation.", null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='raw_import_data',
            field=models.JSONField(blank=True, help_text="Raw JSON data that contributed to this object's creation.", null=True),
        ),
    ]
