# Generated by Django 5.2.2 on 2025-07-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_orderlineitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='source_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='line_items', related_query_name='line_items', to='inventory.sourceitem'),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_items', related_query_name='source_items', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_items', related_query_name='source_items', to='inventory.source'),
        ),
    ]
