# Generated by Django 5.2.2 on 2025-07-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_orderlineitem_source_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('value', models.JSONField()),
            ],
            options={
                'ordering': ['group', 'name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'name'), name='unique_group_name')],
            },
        ),
    ]
