# Generated by Django 5.2.2 on 2025-08-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ingredient',
            field=models.BooleanField(default=False, help_text='Are items in this category used for food?'),
        ),
    ]
