# Generated by Django 5.2.2 on 2025-09-23 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_category_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceitem',
            name='delivered_package_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='delivered_package_amount_text',
            field=models.CharField(blank=True, help_text="An amount that isn't a single number.  Like '9-12#'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='delivered_package_unit_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l0_items', to='inventory.unitsize'),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='level_one_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='level_one_amount_text',
            field=models.CharField(blank=True, help_text="An amount that isn't a single number.  Like '9-12#'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='level_one_unit_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l1_items', to='inventory.unitsize'),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='level_three_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='level_three_amount_text',
            field=models.CharField(blank=True, help_text="An amount that isn't a single number.  Like '9-12#'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='level_three_unit_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l3_items', to='inventory.unitsize'),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='level_two_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='level_two_amount_text',
            field=models.CharField(blank=True, help_text="An amount that isn't a single number.  Like '9-12#'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='level_two_unit_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l2_items', to='inventory.unitsize'),
        ),
    ]
