# Generated by Django 5.2.2 on 2025-09-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_category_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', related_query_name='orders', to='inventory.source'),
        ),
    ]
