# Generated by Django 5.2.2 on 2025-10-16 23:16

from django.utils import timezone
from django.db import migrations, models
from django.db.models import functions


def set_sorta_valid_created_dates(apps, schema_editor):
    Order = apps.get_model("inventory", "Order")
    Order.objects.all().update(created=functions.Cast(
        functions.Concat(models.F('delivered_date'), models.Value(' 12:00:00')),
        output_field=models.DateTimeField()))


update_order_line_item_sql = """
UPDATE inventory_orderlineitem
JOIN inventory_order
    ON inventory_orderlineitem.order_id = inventory_order.id
SET inventory_orderlineitem.created = inventory_order.created;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(set_sorta_valid_created_dates, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(update_order_line_item_sql, reverse_sql=migrations.RunSQL.noop),
    ]
