# Generated by Django 5.2.2 on 2025-09-23 04:05

from django.db import migrations, models


def copy_unit_sizes(apps, schema_editor):
    SourceItem = apps.get_model("inventory", "SourceItem")
    SourceItem.objects.update(
        delivered_package_amount=models.F("unit_amount"),
        delivered_package_amount_text=models.F("unit_amount_text"),
        delivered_package_unit_size=models.F("unit_size"),
        level_one_amount=models.F("subunit_amount"),
        level_one_amount_text=models.F("subunit_amount_text"),
        level_one_unit_size=models.F("subunit_size"),
    )


def uncopy_unit_sizes(apps, schema_editor):
    SourceItem = apps.get_model("inventory", "SourceItem")
    SourceItem.objects.update(
        unit_amount=models.F("delivered_package_amount"),
        unit_amount_text=models.F("delivered_package_amount_text"),
        unit_size=models.F("delivered_package_unit_size"),
        subunit_amount=models.F("level_one_amount"),
        subunit_amount_text=models.F("level_one_amount_text"),
        subunit_size=models.F("level_one_unit_size"),
        delivered_package_amount=None,
        delivered_package_amount_text=None,
        delivered_package_unit_size=None,
        level_one_amount=None,
        level_one_amount_text=None,
        level_one_unit_size=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_sourceitem_delivered_package_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_unit_sizes, reverse_code=uncopy_unit_sizes),
    ]
