# Generated by Django 5.2.2 on 2025-09-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_copy_unit_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceitem',
            name='subunit_amount',
        ),
        migrations.RemoveField(
            model_name='sourceitem',
            name='subunit_amount_text',
        ),
        migrations.RemoveField(
            model_name='sourceitem',
            name='subunit_size',
        ),
        migrations.RemoveField(
            model_name='sourceitem',
            name='unit_amount',
        ),
        migrations.RemoveField(
            model_name='sourceitem',
            name='unit_amount_text',
        ),
        migrations.RemoveField(
            model_name='sourceitem',
            name='unit_size',
        ),
    ]
