# Generated by Django 5.2.2 on 2025-09-07 23:56

import django.db.models.deletion
from django.db import migrations, models



def create_user(apps, username):
    User = apps.get_model("auth", "User")
    password = "Change Me!11!!"
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        user = User.objects.create_user(username, f"{username}@example.com", password)
    return user


def add_permissions(apps, group, app_label):
    Permission = apps.get_model("auth", "Permission")
    group.permissions.add(*Permission.objects.filter(content_type__app_label=app_label))


def create_permission_group(apps, app_label="inventory"):
    Group = apps.get_model("auth", "Group")
    group_name = f"{app_label} manager"
    try:
        group = Group.objects.get(name=group_name)
        return group
    except Group.DoesNotExist:
        group = Group.objects.create(name=group_name)
        return group


def create_default_user(apps, username):
    user = create_user(apps, username)
    inventory_manager_group = create_permission_group(apps, "inventory")
    add_permissions(apps, inventory_manager_group, "inventory")
    meal_planning_manager_group = create_permission_group(apps, "meal_planning")
    add_permissions(apps, meal_planning_manager_group, "meal_planning")
    user.groups.add(inventory_manager_group)
    user.groups.add(meal_planning_manager_group)


def create_default_users(apps, schema_editor):
    usernames = ["usage"]
    for username in usernames:
        create_default_user(apps, username)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_default_user, reverse_code=migrations.RunPython.noop),
    ]
